<?php

namespace AppBundle\Repositories;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Query\Expr;
/**
 * OceanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 */
class OceanRepository extends EntityRepository
{
    /**
     * Get all the users for the datatable rendering
     * @param array $get
     * @param bool $flag
     * @return array|Query
     */
    public function ajaxTable(array $get, $flag = false){
        /* Indexed column (used for fast and accurate table cardinality) */
        $alias = 'u';
        /* DB table to use */
        $tableObjectName = 'AppBundle:Ocean';

        $aColumns = array();
        foreach($get['columns'] as $value) $aColumns[] = $alias .'.'. $value;
        $cb = $this->getEntityManager()
            ->getRepository($tableObjectName)
            ->createQueryBuilder($alias)
            ->select(str_replace(" , ", " ", implode(", ", $aColumns)));

        //Get data to display
        $query = $cb->getQuery();
        if($flag)
            return $query;
        else
            return $query->getResult();
    }
}
